// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openlou/ent/city"
	"openlou/ent/construction"
	"openlou/ent/queue"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConstructionCreate is the builder for creating a Construction entity.
type ConstructionCreate struct {
	config
	mutation *ConstructionMutation
	hooks    []Hook
}

// SetX sets the "x" field.
func (cc *ConstructionCreate) SetX(i int) *ConstructionCreate {
	cc.mutation.SetX(i)
	return cc
}

// SetY sets the "y" field.
func (cc *ConstructionCreate) SetY(i int) *ConstructionCreate {
	cc.mutation.SetY(i)
	return cc
}

// SetRawProduction sets the "raw_production" field.
func (cc *ConstructionCreate) SetRawProduction(i int) *ConstructionCreate {
	cc.mutation.SetRawProduction(i)
	return cc
}

// SetNillableRawProduction sets the "raw_production" field if the given value is not nil.
func (cc *ConstructionCreate) SetNillableRawProduction(i *int) *ConstructionCreate {
	if i != nil {
		cc.SetRawProduction(*i)
	}
	return cc
}

// SetType sets the "type" field.
func (cc *ConstructionCreate) SetType(i int) *ConstructionCreate {
	cc.mutation.SetType(i)
	return cc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (cc *ConstructionCreate) SetNillableType(i *int) *ConstructionCreate {
	if i != nil {
		cc.SetType(*i)
	}
	return cc
}

// SetLevel sets the "level" field.
func (cc *ConstructionCreate) SetLevel(i int) *ConstructionCreate {
	cc.mutation.SetLevel(i)
	return cc
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (cc *ConstructionCreate) SetNillableLevel(i *int) *ConstructionCreate {
	if i != nil {
		cc.SetLevel(*i)
	}
	return cc
}

// SetModifier sets the "modifier" field.
func (cc *ConstructionCreate) SetModifier(f float64) *ConstructionCreate {
	cc.mutation.SetModifier(f)
	return cc
}

// SetNillableModifier sets the "modifier" field if the given value is not nil.
func (cc *ConstructionCreate) SetNillableModifier(f *float64) *ConstructionCreate {
	if f != nil {
		cc.SetModifier(*f)
	}
	return cc
}

// SetNeedRefresh sets the "need_refresh" field.
func (cc *ConstructionCreate) SetNeedRefresh(b bool) *ConstructionCreate {
	cc.mutation.SetNeedRefresh(b)
	return cc
}

// SetNillableNeedRefresh sets the "need_refresh" field if the given value is not nil.
func (cc *ConstructionCreate) SetNillableNeedRefresh(b *bool) *ConstructionCreate {
	if b != nil {
		cc.SetNeedRefresh(*b)
	}
	return cc
}

// SetCityID sets the "city" edge to the City entity by ID.
func (cc *ConstructionCreate) SetCityID(id int) *ConstructionCreate {
	cc.mutation.SetCityID(id)
	return cc
}

// SetNillableCityID sets the "city" edge to the City entity by ID if the given value is not nil.
func (cc *ConstructionCreate) SetNillableCityID(id *int) *ConstructionCreate {
	if id != nil {
		cc = cc.SetCityID(*id)
	}
	return cc
}

// SetCity sets the "city" edge to the City entity.
func (cc *ConstructionCreate) SetCity(c *City) *ConstructionCreate {
	return cc.SetCityID(c.ID)
}

// AddQueueIDs adds the "queue" edge to the Queue entity by IDs.
func (cc *ConstructionCreate) AddQueueIDs(ids ...int) *ConstructionCreate {
	cc.mutation.AddQueueIDs(ids...)
	return cc
}

// AddQueue adds the "queue" edges to the Queue entity.
func (cc *ConstructionCreate) AddQueue(q ...*Queue) *ConstructionCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return cc.AddQueueIDs(ids...)
}

// Mutation returns the ConstructionMutation object of the builder.
func (cc *ConstructionCreate) Mutation() *ConstructionMutation {
	return cc.mutation
}

// Save creates the Construction in the database.
func (cc *ConstructionCreate) Save(ctx context.Context) (*Construction, error) {
	cc.defaults()
	return withHooks[*Construction, ConstructionMutation](ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ConstructionCreate) SaveX(ctx context.Context) *Construction {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ConstructionCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ConstructionCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ConstructionCreate) defaults() {
	if _, ok := cc.mutation.RawProduction(); !ok {
		v := construction.DefaultRawProduction
		cc.mutation.SetRawProduction(v)
	}
	if _, ok := cc.mutation.GetType(); !ok {
		v := construction.DefaultType
		cc.mutation.SetType(v)
	}
	if _, ok := cc.mutation.Level(); !ok {
		v := construction.DefaultLevel
		cc.mutation.SetLevel(v)
	}
	if _, ok := cc.mutation.Modifier(); !ok {
		v := construction.DefaultModifier
		cc.mutation.SetModifier(v)
	}
	if _, ok := cc.mutation.NeedRefresh(); !ok {
		v := construction.DefaultNeedRefresh
		cc.mutation.SetNeedRefresh(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ConstructionCreate) check() error {
	if _, ok := cc.mutation.X(); !ok {
		return &ValidationError{Name: "x", err: errors.New(`ent: missing required field "Construction.x"`)}
	}
	if _, ok := cc.mutation.Y(); !ok {
		return &ValidationError{Name: "y", err: errors.New(`ent: missing required field "Construction.y"`)}
	}
	if _, ok := cc.mutation.RawProduction(); !ok {
		return &ValidationError{Name: "raw_production", err: errors.New(`ent: missing required field "Construction.raw_production"`)}
	}
	if _, ok := cc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Construction.type"`)}
	}
	if _, ok := cc.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Construction.level"`)}
	}
	if _, ok := cc.mutation.Modifier(); !ok {
		return &ValidationError{Name: "modifier", err: errors.New(`ent: missing required field "Construction.modifier"`)}
	}
	if _, ok := cc.mutation.NeedRefresh(); !ok {
		return &ValidationError{Name: "need_refresh", err: errors.New(`ent: missing required field "Construction.need_refresh"`)}
	}
	return nil
}

func (cc *ConstructionCreate) sqlSave(ctx context.Context) (*Construction, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ConstructionCreate) createSpec() (*Construction, *sqlgraph.CreateSpec) {
	var (
		_node = &Construction{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: construction.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: construction.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.X(); ok {
		_spec.SetField(construction.FieldX, field.TypeInt, value)
		_node.X = value
	}
	if value, ok := cc.mutation.Y(); ok {
		_spec.SetField(construction.FieldY, field.TypeInt, value)
		_node.Y = value
	}
	if value, ok := cc.mutation.RawProduction(); ok {
		_spec.SetField(construction.FieldRawProduction, field.TypeInt, value)
		_node.RawProduction = value
	}
	if value, ok := cc.mutation.GetType(); ok {
		_spec.SetField(construction.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := cc.mutation.Level(); ok {
		_spec.SetField(construction.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := cc.mutation.Modifier(); ok {
		_spec.SetField(construction.FieldModifier, field.TypeFloat64, value)
		_node.Modifier = value
	}
	if value, ok := cc.mutation.NeedRefresh(); ok {
		_spec.SetField(construction.FieldNeedRefresh, field.TypeBool, value)
		_node.NeedRefresh = value
	}
	if nodes := cc.mutation.CityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   construction.CityTable,
			Columns: []string{construction.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.city_constructions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   construction.QueueTable,
			Columns: []string{construction.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConstructionCreateBulk is the builder for creating many Construction entities in bulk.
type ConstructionCreateBulk struct {
	config
	builders []*ConstructionCreate
}

// Save creates the Construction entities in the database.
func (ccb *ConstructionCreateBulk) Save(ctx context.Context) ([]*Construction, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Construction, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConstructionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ConstructionCreateBulk) SaveX(ctx context.Context) []*Construction {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ConstructionCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ConstructionCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
