// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/joaopedrosgs/openlou/ent/predicate"
	"github.com/joaopedrosgs/openlou/ent/queue"
)

// QueueDelete is the builder for deleting a Queue entity.
type QueueDelete struct {
	config
	hooks      []Hook
	mutation   *QueueMutation
	predicates []predicate.Queue
}

// Where adds a new predicate to the delete builder.
func (qd *QueueDelete) Where(ps ...predicate.Queue) *QueueDelete {
	qd.predicates = append(qd.predicates, ps...)
	return qd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qd *QueueDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qd.hooks) == 0 {
		affected, err = qd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QueueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qd.mutation = mutation
			affected, err = qd.sqlExec(ctx)
			return affected, err
		})
		for i := len(qd.hooks) - 1; i >= 0; i-- {
			mut = qd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qd *QueueDelete) ExecX(ctx context.Context) int {
	n, err := qd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qd *QueueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: queue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: queue.FieldID,
			},
		},
	}
	if ps := qd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, qd.driver, _spec)
}

// QueueDeleteOne is the builder for deleting a single Queue entity.
type QueueDeleteOne struct {
	qd *QueueDelete
}

// Exec executes the deletion query.
func (qdo *QueueDeleteOne) Exec(ctx context.Context) error {
	n, err := qdo.qd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{queue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qdo *QueueDeleteOne) ExecX(ctx context.Context) {
	qdo.qd.ExecX(ctx)
}
