// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openlou/ent/city"
	"openlou/ent/construction"
	"openlou/ent/predicate"
	"openlou/ent/queue"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QueueUpdate is the builder for updating Queue entities.
type QueueUpdate struct {
	config
	hooks    []Hook
	mutation *QueueMutation
}

// Where appends a list predicates to the QueueUpdate builder.
func (qu *QueueUpdate) Where(ps ...predicate.Queue) *QueueUpdate {
	qu.mutation.Where(ps...)
	return qu
}

// SetCompletion sets the "completion" field.
func (qu *QueueUpdate) SetCompletion(t time.Time) *QueueUpdate {
	qu.mutation.SetCompletion(t)
	return qu
}

// SetAction sets the "action" field.
func (qu *QueueUpdate) SetAction(i int) *QueueUpdate {
	qu.mutation.ResetAction()
	qu.mutation.SetAction(i)
	return qu
}

// AddAction adds i to the "action" field.
func (qu *QueueUpdate) AddAction(i int) *QueueUpdate {
	qu.mutation.AddAction(i)
	return qu
}

// SetOrder sets the "order" field.
func (qu *QueueUpdate) SetOrder(i int) *QueueUpdate {
	qu.mutation.ResetOrder()
	qu.mutation.SetOrder(i)
	return qu
}

// AddOrder adds i to the "order" field.
func (qu *QueueUpdate) AddOrder(i int) *QueueUpdate {
	qu.mutation.AddOrder(i)
	return qu
}

// SetCityID sets the "city" edge to the City entity by ID.
func (qu *QueueUpdate) SetCityID(id int) *QueueUpdate {
	qu.mutation.SetCityID(id)
	return qu
}

// SetNillableCityID sets the "city" edge to the City entity by ID if the given value is not nil.
func (qu *QueueUpdate) SetNillableCityID(id *int) *QueueUpdate {
	if id != nil {
		qu = qu.SetCityID(*id)
	}
	return qu
}

// SetCity sets the "city" edge to the City entity.
func (qu *QueueUpdate) SetCity(c *City) *QueueUpdate {
	return qu.SetCityID(c.ID)
}

// SetConstructionID sets the "construction" edge to the Construction entity by ID.
func (qu *QueueUpdate) SetConstructionID(id int) *QueueUpdate {
	qu.mutation.SetConstructionID(id)
	return qu
}

// SetNillableConstructionID sets the "construction" edge to the Construction entity by ID if the given value is not nil.
func (qu *QueueUpdate) SetNillableConstructionID(id *int) *QueueUpdate {
	if id != nil {
		qu = qu.SetConstructionID(*id)
	}
	return qu
}

// SetConstruction sets the "construction" edge to the Construction entity.
func (qu *QueueUpdate) SetConstruction(c *Construction) *QueueUpdate {
	return qu.SetConstructionID(c.ID)
}

// Mutation returns the QueueMutation object of the builder.
func (qu *QueueUpdate) Mutation() *QueueMutation {
	return qu.mutation
}

// ClearCity clears the "city" edge to the City entity.
func (qu *QueueUpdate) ClearCity() *QueueUpdate {
	qu.mutation.ClearCity()
	return qu
}

// ClearConstruction clears the "construction" edge to the Construction entity.
func (qu *QueueUpdate) ClearConstruction() *QueueUpdate {
	qu.mutation.ClearConstruction()
	return qu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qu *QueueUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, QueueMutation](ctx, qu.sqlSave, qu.mutation, qu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (qu *QueueUpdate) SaveX(ctx context.Context) int {
	affected, err := qu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qu *QueueUpdate) Exec(ctx context.Context) error {
	_, err := qu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qu *QueueUpdate) ExecX(ctx context.Context) {
	if err := qu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (qu *QueueUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   queue.Table,
			Columns: queue.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: queue.FieldID,
			},
		},
	}
	if ps := qu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qu.mutation.Completion(); ok {
		_spec.SetField(queue.FieldCompletion, field.TypeTime, value)
	}
	if value, ok := qu.mutation.Action(); ok {
		_spec.SetField(queue.FieldAction, field.TypeInt, value)
	}
	if value, ok := qu.mutation.AddedAction(); ok {
		_spec.AddField(queue.FieldAction, field.TypeInt, value)
	}
	if value, ok := qu.mutation.Order(); ok {
		_spec.SetField(queue.FieldOrder, field.TypeInt, value)
	}
	if value, ok := qu.mutation.AddedOrder(); ok {
		_spec.AddField(queue.FieldOrder, field.TypeInt, value)
	}
	if qu.mutation.CityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.CityTable,
			Columns: []string{queue.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.CityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.CityTable,
			Columns: []string{queue.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if qu.mutation.ConstructionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.ConstructionTable,
			Columns: []string{queue.ConstructionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.ConstructionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.ConstructionTable,
			Columns: []string{queue.ConstructionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, qu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{queue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	qu.mutation.done = true
	return n, nil
}

// QueueUpdateOne is the builder for updating a single Queue entity.
type QueueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QueueMutation
}

// SetCompletion sets the "completion" field.
func (quo *QueueUpdateOne) SetCompletion(t time.Time) *QueueUpdateOne {
	quo.mutation.SetCompletion(t)
	return quo
}

// SetAction sets the "action" field.
func (quo *QueueUpdateOne) SetAction(i int) *QueueUpdateOne {
	quo.mutation.ResetAction()
	quo.mutation.SetAction(i)
	return quo
}

// AddAction adds i to the "action" field.
func (quo *QueueUpdateOne) AddAction(i int) *QueueUpdateOne {
	quo.mutation.AddAction(i)
	return quo
}

// SetOrder sets the "order" field.
func (quo *QueueUpdateOne) SetOrder(i int) *QueueUpdateOne {
	quo.mutation.ResetOrder()
	quo.mutation.SetOrder(i)
	return quo
}

// AddOrder adds i to the "order" field.
func (quo *QueueUpdateOne) AddOrder(i int) *QueueUpdateOne {
	quo.mutation.AddOrder(i)
	return quo
}

// SetCityID sets the "city" edge to the City entity by ID.
func (quo *QueueUpdateOne) SetCityID(id int) *QueueUpdateOne {
	quo.mutation.SetCityID(id)
	return quo
}

// SetNillableCityID sets the "city" edge to the City entity by ID if the given value is not nil.
func (quo *QueueUpdateOne) SetNillableCityID(id *int) *QueueUpdateOne {
	if id != nil {
		quo = quo.SetCityID(*id)
	}
	return quo
}

// SetCity sets the "city" edge to the City entity.
func (quo *QueueUpdateOne) SetCity(c *City) *QueueUpdateOne {
	return quo.SetCityID(c.ID)
}

// SetConstructionID sets the "construction" edge to the Construction entity by ID.
func (quo *QueueUpdateOne) SetConstructionID(id int) *QueueUpdateOne {
	quo.mutation.SetConstructionID(id)
	return quo
}

// SetNillableConstructionID sets the "construction" edge to the Construction entity by ID if the given value is not nil.
func (quo *QueueUpdateOne) SetNillableConstructionID(id *int) *QueueUpdateOne {
	if id != nil {
		quo = quo.SetConstructionID(*id)
	}
	return quo
}

// SetConstruction sets the "construction" edge to the Construction entity.
func (quo *QueueUpdateOne) SetConstruction(c *Construction) *QueueUpdateOne {
	return quo.SetConstructionID(c.ID)
}

// Mutation returns the QueueMutation object of the builder.
func (quo *QueueUpdateOne) Mutation() *QueueMutation {
	return quo.mutation
}

// ClearCity clears the "city" edge to the City entity.
func (quo *QueueUpdateOne) ClearCity() *QueueUpdateOne {
	quo.mutation.ClearCity()
	return quo
}

// ClearConstruction clears the "construction" edge to the Construction entity.
func (quo *QueueUpdateOne) ClearConstruction() *QueueUpdateOne {
	quo.mutation.ClearConstruction()
	return quo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (quo *QueueUpdateOne) Select(field string, fields ...string) *QueueUpdateOne {
	quo.fields = append([]string{field}, fields...)
	return quo
}

// Save executes the query and returns the updated Queue entity.
func (quo *QueueUpdateOne) Save(ctx context.Context) (*Queue, error) {
	return withHooks[*Queue, QueueMutation](ctx, quo.sqlSave, quo.mutation, quo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (quo *QueueUpdateOne) SaveX(ctx context.Context) *Queue {
	node, err := quo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (quo *QueueUpdateOne) Exec(ctx context.Context) error {
	_, err := quo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (quo *QueueUpdateOne) ExecX(ctx context.Context) {
	if err := quo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (quo *QueueUpdateOne) sqlSave(ctx context.Context) (_node *Queue, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   queue.Table,
			Columns: queue.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: queue.FieldID,
			},
		},
	}
	id, ok := quo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Queue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := quo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, queue.FieldID)
		for _, f := range fields {
			if !queue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != queue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := quo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := quo.mutation.Completion(); ok {
		_spec.SetField(queue.FieldCompletion, field.TypeTime, value)
	}
	if value, ok := quo.mutation.Action(); ok {
		_spec.SetField(queue.FieldAction, field.TypeInt, value)
	}
	if value, ok := quo.mutation.AddedAction(); ok {
		_spec.AddField(queue.FieldAction, field.TypeInt, value)
	}
	if value, ok := quo.mutation.Order(); ok {
		_spec.SetField(queue.FieldOrder, field.TypeInt, value)
	}
	if value, ok := quo.mutation.AddedOrder(); ok {
		_spec.AddField(queue.FieldOrder, field.TypeInt, value)
	}
	if quo.mutation.CityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.CityTable,
			Columns: []string{queue.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.CityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.CityTable,
			Columns: []string{queue.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: city.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if quo.mutation.ConstructionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.ConstructionTable,
			Columns: []string{queue.ConstructionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.ConstructionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   queue.ConstructionTable,
			Columns: []string{queue.ConstructionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: construction.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Queue{config: quo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, quo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{queue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	quo.mutation.done = true
	return _node, nil
}
