// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Construction is the predicate function for construction builders.
type Construction func(*sql.Selector)

// Queue is the predicate function for queue builders.
type Queue func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
