// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Construction is the predicate function for construction builders.
type Construction func(*sql.Selector)

// Queue is the predicate function for queue builders.
type Queue func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
